name: Java CI

on: [push]
    
jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
#  build:
#    name: package
#    runs-on: ubuntu-latest
#    steps:
#    - name: checkout repo
#      uses: actions/checkout@v2
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 8
#    - name: Build with Maven
#      run: mvn clean package -DskipTests=true
#    - name: Build Docker
#      run: docker build -t springboot-admin-server:latest .
#    - name: Push Docker to DockerHub
#      if: success()
#      uses: manusa/actions-publish-docker@master
#      with:
#        name: mayan31370/springboot-admin-server
#        username: mayan31370
#        password: lijing31370
#        tag: ${{ github.ref }}
